os: linux
language: python
services: docker

env:
  - MAKE_SUF=_sp BIN_SUF= TAGS=latest,sp
  - MAKE_SUF=_dp BIN_SUF=_dp TAGS=dp

before_script:
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git 2> /dev/null

script:
  - './ci-util/build-docker.sh : xmjiao/overflow-desktop:$TAGS
         --build-arg GIT_REPO=$GIT_REPO
         --build-arg PEG_REPO=$PEG_REPO
         --build-arg CGT_REPO=$CGT_REPO
         --build-arg PLT_REPO=$PLT_REPO
         --build-arg MAKE_SUF=$MAKE_SUF
         --build-arg BIN_SUF=$BIN_SUF &&
     ./ci-util/trigger-via-api.sh'
