os: linux
sudo: required
language: python
services: docker

env:
  - MAKE_SUF=_sp BIN_SUF= TAGS=ovf_sp
  - MAKE_SUF=_dp BIN_SUF=_dp TAGS=ovf_dp

before_script:
  - sudo echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - git clone --depth=1 https://$GIT_TOKEN@github.com/xmjiao/ci-util.git 2> /dev/null

script:
  - './ci-util/build-docker.sh : xmjiao/overflow-desktop:$TAGS
         --build-arg OVF_REPO=$OVF_REPO
         --build-arg PEG_REPO=$PEG_REPO
         --build-arg CGT_REPO=$CGT_REPO
         --build-arg PLT_REPO=$PLT_REPO
         --build-arg MAKE_SUF=$MAKE_SUF
         --build-arg BIN_SUF=$BIN_SUF --squash &&
     ./ci-util/trigger-via-api.sh'
